node_launcher/constants.py

Added path to bitcoin core for windows users.

Added path to bitcoin core for windows users.

---

node_launcher/command_generator.py
node_launcher/constants.py
node_launcher/gui/network_group_box.py
node_launcher/node_launcher.py
tests/test_gui/test_launch_widget.py

Fixes https://github.com/PierreRochard/node-launcher/issues/14

add Show Macaroons button

---

node_launcher/command_generator.py
node_launcher/constants.py
node_launcher/gui/advertisement_label.py
node_launcher/gui/horizontal_line.py
node_launcher/gui/launch_widget.py
node_launcher/gui/network_group_box.py
tests/test_gui/test_launch_widget.py

fixes https://github.com/PierreRochard/node-launcher/issues/13

implement copy lncli

---

node_launcher/command_generator.py
node_launcher/gui/network_group_box.py
tests/test_gui/test_launch_widget.py

Fixes https://github.com/PierreRochard/node-launcher/issues/19
Also made for Joule @wbobeirne !

Add copy LND REST address button

---

README.md
node_launcher/__version__.py
node_launcher/command_generator.py
node_launcher/configuration/bitcoin_configuration.py
node_launcher/configuration/configuration_file.py
node_launcher/configuration/hard_drives.py
node_launcher/constants.py
node_launcher/gui/data_directory.py
node_launcher/gui/launch_widget.py
node_launcher/gui/network_group_box.py
node_launcher/node_launcher.py
node_launcher/node_software/bitcoin_software.py
node_launcher/node_software/node_software.py
node_launcher/utilities.py
requirements.txt
tests/test_configuration/test_bitcoin_configuration.py
tests/test_configuration/test_configuration_file.py
tests/test_configuration/test_hard_drives.py
tests/test_gui/test_launch_widget.py

Fixes https://github.com/PierreRochard/node-launcher/issues/15

Add the ability to modify the data directory

---

node_launcher/command_generator.py
node_launcher/gui/network_group_box.py
run-windows.spec
tests/test_gui/test_network_group_box.py

Fixes https://github.com/PierreRochard/node-launcher/issues/25

Grpc url button

---

node_launcher/gui/network_group_box.py
node_launcher/gui/seed_dialog.py
node_launcher/lnd_client/lnd_client.py
requirements.txt
tests/test_gui/test_seed_dialog.py

fixes https://github.com/PierreRochard/node-launcher/issues/35

add password and seed backup

---

README.md
node_launcher/node_set/bitcoin.py
node_launcher/node_set/lnd_client/lnd_client.py

fixes https://github.com/PierreRochard/node-launcher/issues/40

Macos bugs

---

node_launcher/constants.py
node_launcher/gui/advanced/advanced_widget.py
node_launcher/gui/advanced/versions_layout.py
node_launcher/gui/components/selectable_text.py
node_launcher/gui/network_buttons/nodes_layout.py
node_launcher/gui/network_buttons/zap_layout.py
node_launcher/node_set/lnd.py
tests/test_gui/test_advanced/test_advanced_widget.py
tests/test_gui/test_advanced/test_versions_layout.py
tools/channel_balancer.py

Fixes https://github.com/PierreRochard/node-launcher/issues/97

Add version numbers in the Advanced window

---

node_launcher/node_set/lnd.py

Sending SIGTERM instead of SIGINT on windows.

Fixing bug where windows does not support SIGINT

---

node_launcher/gui/components/seed_dialog.py

This should fix issue #96 
The code is now starting the printer setup (and prints the mnemonic seed) instead of saving a print screen of it.
(I'm from Justin's army and this is all new to me, so please let me know if I missed anything in the contribution.)

Fix issue #96 - Printing of Mnemonic Seed

---

node_launcher/node_set/lnd.py
node_launcher/services/node_software.py

This is useful for adding to your shell `path`

 maintain a bin directory that links to the latest version of commands

---

node_launcher/constants.py
node_launcher/node_set/lnd.py
node_launcher/services/configuration_file.py
node_launcher/services/node_software.py
node_launcher/utilities/ip_address.py
tests/test_node_set/test_lnd.py

Also removes the `tlsextraip` default

 Enable list assignment for config file to enable LND's multi-listening

---

node_launcher/constants.py
node_launcher/gui/main_widget.py
node_launcher/gui/network_buttons/network_widget.py
node_launcher/services/bitcoin_software.py
node_launcher/services/launcher_software.py
node_launcher/services/lnd_software.py

Removes network calls or makes them async with a timer

Improve app start performance

---

node_launcher/constants.py
node_launcher/node_set/bitcoin.py

Fixes https://github.com/lightning-power-users/node-launcher/issues/168
Fixes https://github.com/lightning-power-users/node-launcher/issues/169
Fixes https://github.com/lightning-power-users/node-launcher/issues/163

5.5.1 bug fixes

---

node_launcher/node_set/lnd.py
node_launcher/node_set/lnd_client/lnd_client.py
node_launcher/services/configuration_file.py

 lnddir is not a valid configuration file key

---

node_launcher/node_set/lnd.py
tests/test_node_set/test_lnd.py

Fixes https://github.com/lightning-power-users/node-launcher/issues/178

fix bug from having multiple listen conf items

---

node_launcher/gui/system_tray_widgets/lnd_output_widget.py

Fixes https://github.com/lightning-power-users/node-launcher/issues/67

improve autorestart for LND

---

node_launcher/node_set/lnd.py

Fixes https://github.com/lightning-power-users/node-launcher/issues/223

Default tlsextraip to localhost

---

node_launcher/node_set/bitcoin.py

Fixes https://github.com/lightning-power-users/node-launcher/issues/260

switch to default datadir if old one not found

---

node_launcher/node_set/bitcoin.py

Fixes https://github.com/lightning-power-users/node-launcher/issues/262

Config file can be changed without zmq port conf being present

---

node_launcher/gui/system_tray_widgets/bitcoind_output_widget.py
node_launcher/gui/system_tray_widgets/lnd_output_widget.py

Fixes https://github.com/lightning-power-users/node-launcher/issues/254

Fix divide by zero bug

---

node_launcher/gui/application.py
node_launcher/gui/utilities.py

Fixes https://github.com/lightning-power-users/node-launcher/issues/278

fix check version message box creation

---

node_launcher/constants.py

Signed-off-by: willcl-ark <will8clark@gmail.com>

Updated LND version to v0.6-beta-rc4 as rc3 no longer hosted

---

node_launcher/gui/system_tray_widgets/advanced/zap_layout.py

Fixes https://github.com/lightning-power-users/node-launcher/issues/272

Update the Zap Desktop lndconnect link format

---

node_launcher/gui/application.py
node_launcher/gui/menu/manage_lnd/lnd_output_tab.py
node_launcher/gui/system_tray.py

This wraps the Qt method interface to be more ergonomic

refactor system tray show message

---

tests/test_gui/test_menu/test_menu.py

This fixes the `test_menu.py` tests

Add to magicmock fixture to handle new network tab system

---

node_launcher/constants.py

small patch attempting to close #367

update tor target release

---

ux.md

My suggestions were too large for a comment, so I made a PR. :) This is something I wanted for a while. We should discuss it at the other PR, I think.

Added suggestions and other features to the vision doc
